## Умова:
До пункту видачі надійшли вироби з такими характеристиками:
Всього виробів – 13000 одиниць, з них виготовлено на першому заводі — 8000 од., вагою 13 кг., зі стандартним відхиленням по вазі 0.5 кг.. На другому — 5000 од., вагою 12 кг., зі стандартним відхиленням по вазі 0.7 кг. Доля якісних виробів, вироблених на першому заводі, становить 0.85. Доля якісних виробів, вироблених на другому заводі 0,8.

## Завдання: 
Написати код, з використанням EM-алгоритму, для визначення ймовірності, на якому заводі був вироблений виріб.


In [98]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random
from scipy.stats import multivariate_normal

In [99]:
from sklearn.mixture import GaussianMixture
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
from numpy import random 
from pandas import DataFrame
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

In [100]:
import random as rand

def gen_data(mean, stdd, samples):
    data = [rand.normalvariate(mean, stdd) for i in range(samples)]
    return data

data = gen_data(13, 0.5, 8000) + gen_data(12, 0.7, 5000)

x = np.array(data)
x

array([13.36176069, 12.66479051, 13.36327893, ..., 12.56062896,
       12.52066449, 12.24617963])

In [101]:
gm = GaussianMixture(n_components=2).fit(x.reshape(-1, 1))
gm.get_params()

{'covariance_type': 'full',
 'init_params': 'kmeans',
 'max_iter': 100,
 'means_init': None,
 'n_components': 2,
 'n_init': 1,
 'precisions_init': None,
 'random_state': None,
 'reg_covar': 1e-06,
 'tol': 0.001,
 'verbose': 0,
 'verbose_interval': 10,
 'warm_start': False,
 'weights_init': None}

In [102]:
centers = gm.means_
print(centers)

[[13.00585015]
 [11.9267767 ]]


In [103]:
pred = gm.predict(x.reshape(-1, 1))

In [104]:
print(pred)

[0 0 0 ... 0 0 1]


In [123]:
print('1 завод:',list(pred).count(0)/13000)
print('2 завод:',list(pred).count(1)/13000)

1 завод: 0.6933076923076923
2 завод: 0.3066923076923077


In [122]:
5000/13000

0.38461538461538464

In [110]:
print(metrics.rand_score(x, list(pred)))
print(metrics.normalized_mutual_info_score(x, list(pred)))
print(metrics.mutual_info_score(x, list(pred)))

0.4252969873422216
0.12219652235669565
0.6164284908761049
