## Умова:
До пункту видачі надійшли вироби з такими характеристиками:
Всього виробів – 13000 одиниць, з них виготовлено на першому заводі — 8000 од., вагою 13 кг., зі стандартним відхиленням по вазі 0.5 кг.. На другому — 5000 од., вагою 12 кг., зі стандартним відхиленням по вазі 0.7 кг. Доля якісних виробів, вироблених на першому заводі, становить 0.85. Доля якісних виробів, вироблених на другому заводі 0,8.

## Завдання: 
Написати код, з використанням EM-алгоритму, для визначення ймовірності, на якому заводі був вироблений виріб.


In [134]:
import numpy as np
from numpy import random
from scipy.stats import multivariate_normal

In [135]:
from sklearn.mixture import GaussianMixture
from numpy import random 
from pandas import DataFrame
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

In [136]:
import random as rand

def gen_data(mean, stdd, samples):
    data = [rand.normalvariate(mean, stdd) for i in range(samples)]
    return data

data = gen_data(13, 0.5, 8000) + gen_data(12, 0.7, 5000)

x = np.array(data)
x

array([13.59568506, 13.33175483, 13.01877487, ..., 13.07419062,
       12.79921151, 12.08595874])

In [137]:
gm = GaussianMixture(n_components=2).fit(x.reshape(-1, 1))
gm.get_params()

{'covariance_type': 'full',
 'init_params': 'kmeans',
 'max_iter': 100,
 'means_init': None,
 'n_components': 2,
 'n_init': 1,
 'precisions_init': None,
 'random_state': None,
 'reg_covar': 1e-06,
 'tol': 0.001,
 'verbose': 0,
 'verbose_interval': 10,
 'warm_start': False,
 'weights_init': None}

In [138]:
centers = gm.means_
print(centers)

[[13.00534549]
 [11.92081272]]


In [139]:
pred = gm.predict(x.reshape(-1, 1))

In [140]:
print(pred)

[0 0 0 ... 0 0 1]


In [141]:
print('1 завод:',list(pred).count(0)/13000)
print('2 завод:',list(pred).count(1)/13000)

1 завод: 0.6937692307692308
2 завод: 0.30623076923076925


In [143]:
print(metrics.rand_score(x, list(pred)))
print(metrics.normalized_mutual_info_score(x, list(pred)))
print(metrics.mutual_info_score(x, list(pred)))

0.42493965808020734
0.12212636217844225
0.6160515457162291
